# Generated by Django 4.2.16 on 2024-09-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newstype_type_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstype',
            name='type_news',
            field=models.CharField(choices=[('M', 'MainNews'), ('S', 'SecondaryNews'), ('T', 'ThirdNews'), ('N', 'Normal')], default='N', max_length=20),
        ),
    ]
