# Generated by Django 4.2.16 on 2024-09-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Authors', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterField(
            model_name='authors',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
