# Generated by Django 4.2.16 on 2024-09-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_authors_options_alter_authors_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='matiral_status',
            new_name='marital_status',
        ),
    ]
