# Generated by Django 4.2.16 on 2024-09-15 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0004_authors_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='hometown',
            field=models.CharField(choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('Distrito Federal', 'Distrito Federal'), ('Espírito Santo', 'Espírito Santo'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Minas Gerais', 'Minas Gerais'), ('Pará ', 'Pará '), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('Santa Catarina', 'Santa Catarina'), ('São Paulo', 'São Paulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], default='', max_length=19, verbose_name='Hometown'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=10, verbose_name='Current City'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/photo_profile', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='profile_status',
            field=models.CharField(choices=[('Público', 'Público'), ('Privado', 'Privado')], max_length=10, verbose_name='Profile Status'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
