# Generated by Django 4.2.16 on 2024-09-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postblog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/covers/%Y/%m/%d'),
        ),
    ]
